language: csharp
solution: starling.sln
mono: none
dotnet: 2.2.300
dist: xenial

before_install:
    - ./install-z3.sh
    - ./install-hsf.sh

cache:
    directories:
        - $TRAVIS_BUILD_DIR/z3-z3-4.8.5/install/lib
        - $TRAVIS_BUILD_DIR/hsf/qarmc

script:
    - export PATH=$PATH:$TRAVIS_BUILD_DIR/hsf/qarmc/bin
    - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/z3-z3-4.8.5/install/lib
    - dotnet restore
    - dotnet build
    - dotnet test
    - ./regress.py -vg

